#!/bin/bash

usage() {
	echo "$0 [part of username] [--file=[part of full path to file]]"
	exit 1
}
#pid_usr_ip='smbstatus.log'
pid_usr_ip='/temp/piu.list'
userlist='/tmp/userlist.list'
filelist='/tmp/filelist.list'
null=/dev/null

smbstatus > $pid_usr_ip

function list-users {
   cat $pid_usr_ip | awk 'BEGIN {
         flag=0
      } {
         if (flag==2 && $2!~".\\$") {
            split($NF,ip,":")
            print $1,$2,ip[2]
         }
         if ($0~"^$" || $0~"--------------") flag++
      }' > $userlist
}

function list-files {
	cat $pid_usr_ip | awk 'BEGIN {
		flag=0
	} {
		if ($8!="" && $8!="\\\\.") {
			file=""
			for (i=8; i<=NF-5;i++) file=file" "$i
			printf("%s|%s|\n",$1,file)
		}
		if ($0~"^$" || $0~"------------------------") flag++
	}' | sort | uniq | grep -v "||" | grep -v "| .|" > $filelist
}

function get-wksname {
   if [[ -z  $(host $1 | awk '{ if (NR>1) print $NF}') ]];then
      echo $1
   else
      echo  $(host $1 | awk '{ if (NR>1) print $NF}')
   fi
}

function parse-users {
	cat $userlist | awk '{print $2}' | sort | uniq | grep -E $1 2>$null || return 1
}

function get-filelikeparser {
	part="^[0-9]+\| .*$1.*\|$"
	cat $filelist | grep -iE "$part" | while read i; do
		pid=$(echo -e "$i" | awk -F"|" '{print $1}')
		file=$(echo -e "$i" | awk -F"|" '{print $2}')
		user=$(get-info pid2user $pid)
		wks=$(get-wksname $(get-info pid2ip $pid))
		printf "%-15s %-25s %s\n" $user  $wks "$file"
	done 
}

function get-online {
	echo online	
}

function get-info {
	command_=$1
	obj_=$2
	#echo $obj_ $command_
	case $command_ in
		user2pid)
			cat $userlist | awk -v user=$obj_ '{if ($2==user) print $1}'
			;;
		pid2ip)
			cat $userlist | awk -v pid=$obj_ '{if ($1==pid) print $3}'
			;;
		pid2user)
			cat $userlist | awk -v pid=$obj_ '{if ($1==pid) print $2}'
			;;
		pid2files)
			cat $filelist | awk -F"|" -v pid=$obj_ '{if ($1==pid) print $2}'
			;;
	esac 
}

list-users
list-files

[[ -z $* ]] && usage

while [ $# -gt 0 ];do
	case "$1" in
		+f)
			fs=1
			;;
		--file=*)
			t="$(echo $1 | sed 's/^--file=//1')"
			parsers="$t\n$parsers"
			unset $t
			;;
		-online)
			online=1
			;;
		*)
			users="$1\n$users"
	esac
	shift
done

[[ ! -z "$users" ]] && {
	_users='/tmp/_users'
	echo ==========================================
	printf "%-15s %-25s \n" "Username" "Wks"
	echo ==========================================
	echo -e "$users" | while read i;do
		[[ ! -z "$i" ]] && parse-users $i 
	done > $_users
	[[ -z "$(cat $_users)" ]] && {
		echo not found users
		exit 1
	}
	echo -e "$(cat $_users)" | while read i;do
		pid=$(get-info user2pid $i)
		echo -e "$pid" | while read j;do
			ip=$(get-info pid2ip $j)
			printf "%-15s %-25s \n" $i $(get-wksname $ip)
			[[ $fs -eq "1" ]] && get-info pid2files $pid
		done		
	done
	[[ -a $_users ]] && rm $_users
	unset _users
}

[[ ! -z "$parsers" ]] && {
	_parsers='/tmp/_parsers'
	echo ==============================================================================
	printf "%-15s %-25s %s\n" "Username" "wks" "file"
	echo ==============================================================================
	echo -e "$parsers" | while read i;do
		[[ ! -z "$i" ]] && get-filelikeparser $i
	done | sort | uniq
	[[ -a $_parsers ]] && rm $_parsers
	unset _parsers
}

